<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="MSI" failures="1" tests="1" name="SeleniumProject_Sept24" time="0.312" errors="0" timestamp="2024-10-01T15:29:24 IST">
  <testcase classname="com.automation.testng.LoginTest" name="averifyUserCanLogout" time="0.11">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Test1] but found [Test],
	expected [true] but found [false],
	expected [20] but found [10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Test1] but found [Test],
expected [true] but found [false],
expected [20] but found [10]
at com.automation.testng.LoginTest.averifyUserCanLogout(LoginTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- averifyUserCanLogout -->
  <testcase classname="com.automation.testng.LoginTest" name="bverifyUserCanLogin" time="0.0">
    <ignored/>
  </testcase> <!-- bverifyUserCanLogin -->
  <testcase classname="com.automation.testng.LoginTest" name="cverifyUserCannotLoginWithInvalidCred" time="0.0">
    <ignored/>
  </testcase> <!-- cverifyUserCannotLoginWithInvalidCred -->
</testsuite> <!-- SeleniumProject_Sept24 -->
